sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pelegbub/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true pelegbub/react-test npm test

after_success:
  - docker build -t pelegbub/multi-client ./clinet
  - docker build -t pelegbub/multi-nginx ./nginx
  - docker build -t pelegbub/multi-server ./server 
  - docker build -t pelegbub/multi-worker ./worker
#log in to the docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
- docker push pelegbub/multi-client
- docker push pelegbub/multi-ngnix 
- docker push pelegbub/multi-sever
- docker push pelegbub/multi-worker




  