sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pelegb999/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pelegb999/react-test npm test

after_success:
  - docker build -t pelegb999/multi-client ./client
  - docker build -t pelegb999/multi-nginx ./nginx
  - docker build -t pelegb999/multi-server ./server
  - docker build -t pelegb999/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pelegb999/multi-client
  - docker push pelegb999/multi-nginx
  - docker push pelegb999/multi-server
  - docker push pelegb999/multi-worker

#deploy to aws

deploy:
  provider: elasticbeanstlak
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-eu-central-1-606384754396
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
